

--Este Script  muestra el listado de columnas con el tipo de  una 
--ejecucion de un procedimiento almacenado o una consulta 

DECLARE @SQLTEXT  VARCHAR(MAX) = 'SELECT  NUM, DET_CODIGO_CONSUMO, PESO_BRUTO, ENC_CODIGO_CONSUMO, PESO_BRUTO_SOBRANTE, BAR_CODE_CONSUMO,	TIPO_CONSUMO, NO_ROLLO_CONSUMO,
		
		 		_DET_CODIGO,_BAR_CODE_CONSUMIDO, _ENC_CODIGO_CONSUMIDO, _PESO_NETO,  _PESO_NETO_CONSUMIDO,  _FECHA, _NO_ORDEN, _PROCESO, _SUBPROCESO,  	
				(SELECT COD_PRODUCTO FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN AND PROCESO=C3._PROCESO)AS _COD_PRODUCTO,
				(SELECT DES_PRODUCTO FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN  AND PROCESO=C3._PROCESO)AS _DES_PRODUCTO,
				(SELECT COD_CLIENTE FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN  AND PROCESO=C3._PROCESO)AS _COD_CLIENTE,
				(SELECT NOM_CLIENTE FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN AND PROCESO=C3._PROCESO)AS _NOM_CLIENTE,
				(SELECT ORDEN_ALTERNA FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN  AND PROCESO=C3._PROCESO)AS _ORDEN_ALTERNA,
				(SELECT COD_RUTA FROM ORDEN_PRODUCCION WHERE  NO_ORDEN=C3._NO_ORDEN  AND PROCESO=C3._PROCESO)AS _COD_RUTA
				
		FROM(
			SELECT *,
				(SELECT FECHA FROM ENC_PRODUCCION WHERE  ENC_CODIGO=C2._ENC_CODIGO_CONSUMIDO)AS _FECHA,
				(SELECT NO_ORDEN FROM ENC_PRODUCCION WHERE  ENC_CODIGO=C2._ENC_CODIGO_CONSUMIDO)AS _NO_ORDEN,
				(SELECT PROCESO FROM ENC_PRODUCCION WHERE  ENC_CODIGO=C2._ENC_CODIGO_CONSUMIDO)AS _PROCESO,
				(SELECT SUBPROCESO FROM ENC_PRODUCCION WHERE  ENC_CODIGO=C2._ENC_CODIGO_CONSUMIDO)AS _SUBPROCESO
					
			FROM(
			
					SELECT NUM, PESO_BRUTO, ENC_CODIGO_CONSUMO, PESO_BRUTO_SOBRANTE, BAR_CODE_CONSUMO,
					(CASE WHEN TIPO_CONSUMO=1 THEN '+'''PARCIAL'+''' WHEN TIPO_CONSUMO=2 THEN '+'''TOTAL'+''' ELSE NULL END) AS TIPO_CONSUMO,  
					(SELECT NO_ROLLO FROM DET_PRODUCCION WHERE BAR_CODE = A.BAR_CODE_CONSUMO) AS NO_ROLLO_CONSUMO, 
					(SELECT DET_CODIGO FROM DET_PRODUCCION WHERE BAR_CODE = A.BAR_CODE_CONSUMO) AS DET_CODIGO_CONSUMO, 

					   
					--INFO DEL ROLLO CONSUMIDO
					DET_CODIGO AS _DET_CODIGO,
					(SELECT BAR_CODE FROM DET_PRODUCCION WHERE DET_CODIGO = A.DET_CODIGO) AS _BAR_CODE_CONSUMIDO,
					(SELECT ENC_CODIGO FROM DET_PRODUCCION WHERE DET_CODIGO = A.DET_CODIGO) AS _ENC_CODIGO_CONSUMIDO,
					(SELECT (PESO_NETO) FROM DET_PRODUCCION WHERE DET_CODIGO = A.DET_CODIGO) AS _PESO_NETO,
					(SELECT (PESO_NETO - (PESO_NETO*PORC_CONSUMO)) FROM DET_PRODUCCION WHERE DET_CODIGO = A.DET_CODIGO) AS _PESO_NETO_CONSUMIDO
					     
				 FROM DET_PRODUCCION_CONSUMO AS A
				 WHERE NUM = 1
			)AS C2
		)AS C3  '

 
select Name as Nombre, system_type_name as Tipo
  from sys.dm_exec_describe_first_result_set
		( @SQLTEXT, null, 0)
 order by column_ordinal



 