
	SELECT *,
			(SELECT DESCRIPCION FROM SMANT_5S_LUGARES WHERE COD_LUGAR = C4.COD_LUGAR)AS DESC_LUGAR
	FROM(
		SELECT FECHA, (SELECT DESCRIPCION FROM SMANT_5S_AREAS_MEJORA WHERE COD_AREA =C3.COD_AREA )AS DESC_AREA, 
					  (SELECT COD_LUGAR FROM SMANT_5S_AREAS_MEJORA WHERE COD_AREA =C3.COD_AREA )AS COD_LUGAR, 
				[S-1], [S-2], [S-3], [S-4], [S-5], ([S-1] + [S-2] + [S-3] + [S-4] + [S-5])AS TOTAL, 50 AS META
		FROM(
			SELECT *
			FROM(

				SELECT FECHA, COD_AREA,  TIPO_5S, SUM(CAST(VALOR AS INT))AS VALOR 		
				FROM(
					SELECT FECHA, COD_PREGUNTA,  
						   (SELECT TIPO_5S FROM  SMANT_5S_PREGUNTAS WHERE COD_PREGUNTA = A.COD_PREGUNTA )AS TIPO_5S,
						   (SELECT COD_AREA FROM  SMANT_5S_PREGUNTAS WHERE COD_PREGUNTA = A.COD_PREGUNTA )AS COD_AREA,	   
						   DESCRIPCION,
						   VALOR 
					FROM SMANT_5S_EVALUACION AS A
				)AS C1
				GROUP BY FECHA, TIPO_5S,COD_AREA

			)AS C2 PIVOT(SUM(VALOR)FOR TIPO_5S IN ([S-1], [S-2], [S-3], [S-4], [S-5])) P
		)AS C3
	)AS C4
	









		
	SELECT FECHA,  TIPO_5S, 
		   (SELECT TOP 1 DESCRIPCION FROM SMANT_5S_AREAS WHERE TIPO_5S = C5.TIPO_5S)AS DESC_5S,
		   MAX([FLEXIBLE]) AS [FLEXIBLE], 
		   MAX([SACOS]) AS [SACOS], 
		   MAX([MANTENIMIENTO]) AS [MANTENIMIENTO], 
		   MAX([BODEGA])AS   [BODEGA]
	FROM(
		SELECT *
		FROM(
			SELECT FECHA, TIPO_5S, VALOR, 
					(SELECT DESCRIPCION FROM SMANT_5S_LUGARES WHERE COD_LUGAR =C3.COD_LUGAR )AS DESC_LUGAR
			FROM(
				
				SELECT FECHA, TIPO_5S, VALOR, 
						(SELECT COD_LUGAR FROM SMANT_5S_AREAS_MEJORA WHERE COD_AREA =C2.COD_AREA )AS COD_LUGAR
				FROM(
					SELECT FECHA, COD_AREA,  TIPO_5S, SUM(CAST(VALOR AS INT))AS VALOR 		
					FROM(
						SELECT FECHA, COD_PREGUNTA,  
							   (SELECT TIPO_5S FROM  SMANT_5S_PREGUNTAS WHERE COD_PREGUNTA = A.COD_PREGUNTA )AS TIPO_5S,
							   (SELECT COD_AREA FROM  SMANT_5S_PREGUNTAS WHERE COD_PREGUNTA = A.COD_PREGUNTA )AS COD_AREA,	   
							   DESCRIPCION,
							   VALOR 
						FROM SMANT_5S_EVALUACION AS A
						WHERE FECHA = '02-08-2019'				
					)AS C1
					GROUP BY FECHA, COD_AREA,  TIPO_5S			
				)AS C2
			)AS C3
		)AS C4 PIVOT(AVG(VALOR)FOR DESC_LUGAR IN ([FLEXIBLE], [SACOS], [MANTENIMIENTO], [BODEGA])) P
	)AS C5
	GROUP BY FECHA,  TIPO_5S
		
		
		
		






