

SELECT *, ISNULL(DATEDIFF(MINUTE,FECHA_2,FECHA_1),0)AS DIF_MINUTOS
FROM(
	SELECT A.ESTADO, A.FECHA AS FECHA_1, B.FECHA AS FECHA_2  FROM 
	(
		SELECT ROW_NUMBER() OVER(ORDER BY FECHA ASC)AS NUM, ESTADO, FECHA 
		FROM APP_SISTEMAS.DBO.SMASR_SEGUIMIENTO_SOLICITUD_DETALLE
	)AS A
	LEFT JOIN 

	(
		SELECT ROW_NUMBER() OVER(ORDER BY FECHA ASC)AS NUM, ESTADO, FECHA 
		FROM APP_SISTEMAS.DBO.SMASR_SEGUIMIENTO_SOLICITUD_DETALLE	
	)AS B
	ON (A.NUM-1=B.NUM)
)AS C1

