

--EXECUTE ADD_WORK_ORDER 4,'OPR-04237-18',50.00, 80000.00

ALTER PROCEDURE ADD_WORK_ORDER (@NumOrder smallint, @WORK_ORDER NVARCHAR(30), @Hrs decimal(12,2)=NULL, @Libras Decimal(15,2)=NULL)
AS
BEGIN


	DECLARE @Colores smallint = NULL, @Rodillo Decimal(12,2)=NULL
	DECLARE @T_Seteo Decimal(12,2)=0.0


	--OBTENGO VALORES DE CAMPOS ESPECIALES DE IMPRENTA
	IF ((Select LEFT(RESOURCE_ID,1) FROM VMFGPN.DBO.OPERATION WHERE WORKORDER_BASE_ID=@WORK_ORDER)='I')
	BEGIN
		 (SELECT TOP 1 @Rodillo = ISNULL(USER_1,'N/A')  FROM VMFGPN.DBO.OPERATION WHERE WORKORDER_BASE_ID=@WORK_ORDER )
		 (SELECT @Colores = Count(PART_ID)  FROM VMFGPN.DBO.REQUIREMENT WHERE WORKORDER_BASE_ID=@WORK_ORDER  and User_3 is not null)	

	END
	
	--SI LA ORDEN NO TRAE HRS, OBTENGO EL TIEMPO DESDE LA OPERACION Y EL TIEMPO DE SETEO 
	IF (@Hrs is NULL)
	begin
		Select @Hrs=(RUN_HRS+SETUP_HRS), @T_Seteo=SETUP_HRS  FROM VMFGPN.DBO.OPERATION WHERE WORKORDER_BASE_ID=@WORK_ORDER
	end
	
		

INSERT INTO PLANNING_PRG_TEMP_ORDER

	SELECT @NumOrder as NUMORDER,*,
				(SELECT NAME FROM VMFGPN.DBO.CUSTOMER as c where ID =C1.CUSTOMER_ID )AS NomCliente,
				(SELECT PRODUCT_CODE FROM VMFGPN.DBO.PART WHERE ID=C1.PART_ID)AS PRODUCT_CODE,
				(SELECT DESCRIPTION FROM VMFGPN.DBO.PART WHERE ID=C1.PART_ID)AS DESC_PART_ID
		FROM (

			SELECT CONVERT(VARCHAR(10),CREATE_DATE, 103) AS F_CREADA, BASE_ID, 	PART_ID AS CO_PRODUCTO, 
					--Condiciono el Codigo del Part_id para obtener el Codigo de Producto Compatible con el ID del PART
					CASE WHEN ISNUMERIC(LEFT(PART_ID,1)) = 0 THEN LTRIM(RTRIM(SUBSTRING(a.PART_ID,3,LEN(a.PART_ID)-2))) 
						 WHEN ISNUMERIC(LEFT(PART_ID,1)) = 1 THEN PART_ID 
					END AS PART_ID,
					(SELECT DESCRIPTION FROM VMFGPN.DBO.PART WHERE ID=a.PART_ID)AS DESC_CO_PRODUCTO,
					(SELECT STRING_VAL FROM VMFGPN.DBO.user_def_fields AS ud WHERE ud.DOCUMENT_ID=a.PART_ID AND ID='00038')AS CUSTOMER_ID,
					 CONVERT(VARCHAR(10),DESIRED_RLS_DATE,103)AS F_ENTRADA,CONVERT(VARCHAR(10),DESIRED_WANT_DATE,103)AS F_REQUERIDA, 
					b.RESOURCE_ID AS MAQUINA, b.RUN AS LibrasXHora, @Hrs AS T_TRABAJO, @T_Seteo AS T_SETEO, @Hrs AS TOT_HRSTRABAJO, 
					@Libras as LIBRAS, CONVERT(VARCHAR(10),a.CLOSE_DATE,103)AS F_CERRADA, a.STATUS, 
				   a.USER_1 AS Ancho, a.USER_2 AS Tipo, a.USER_3 AS Espesor, @Colores AS Colores,  @Rodillo as Rodillo,
				   a.USER_4 as Peso_Metro,  a.USER_5 AS Orden_Otro
		   
			FROM  
			VMFGPN.DBO.WORK_ORDER AS a
			inner join VMFGPN.DBO.OPERATION AS b on (a.BASE_ID=B.WORKORDER_BASE_ID)
			WHERE a.BASE_ID = @WORK_ORDER
		)AS C1



END 
GO 

	